# Generated by Django 2.0.5 on 2019-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsinInfo',
            fields=[
                ('asin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant', models.CharField(blank=True, max_length=20, null=True)),
                ('sellers', models.CharField(blank=True, max_length=5, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=10, null=True)),
                ('star', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery', models.CharField(blank=True, max_length=32, null=True)),
                ('build_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('collection', models.CharField(blank=True, max_length=1, null=True)),
                ('alibaba_link', models.CharField(blank=True, max_length=200, null=True)),
                ('monitor', models.CharField(blank=True, max_length=32, null=True)),
                ('readinfo', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'asin_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GmMonitor',
            fields=[
                ('asin', models.CharField(blank=True, max_length=15, null=True)),
                ('update_time', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('ranks', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('seller', models.CharField(blank=True, max_length=20, null=True)),
                ('price1', models.CharField(blank=True, max_length=20, null=True)),
                ('seller1', models.CharField(blank=True, max_length=20, null=True)),
                ('registered', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'gm_monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorAsin',
            fields=[
                ('asin', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('alibaba_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'monitor_asin',
                'managed': False,
            },
        ),
    ]
